### ISSUE TITLE
Weird Physics behavior

### ISSUE THREAD

**Issue by AhhhFreshMeat** [Joshua-Ashton/VPhysics-Jolt#18]
Small physics objects(possibly larger) appear to rotate chaotically when near/inside player. Has an effect of the object magnetizing towards the player.

https://user-images.githubusercontent.com/90083515/187143481-81ed6c52-d2fa-4910-952b-99bdcb20c8f0.mp4

https://user-images.githubusercontent.com/90083515/187143466-c5f8233b-3d46-49da-a115-06c11d2ffb44.mp4

I am running this on a dedicated srcds_win64 ( Garry's mod )

**Comment by jonjimjoebobbillybobob** [comment]
The physics replacement is absolutely amazing and would be ideal for me to use on my server, unfortunately I use projectile based weapons instead of hitscan and I am certain this issue is the reason why the projectiles fly in random directions or rotate spastically. This seems to happen even if I force the projectile to have no collisions with the player.

I don't expect this physics replacement to cater towards such niche mechanics but if it's possible to fix or alleviate this issue it would be absolutely fantastic.

**Comment by Slartibarty** [comment]
This is caused by the quick and dirty code I wrote just before release to allow players to stand on things and apply downwards force on them, I don't check to see if you're actually standing on the thing before applying force, so just getting close enough to props is enough to apply force on them, will see if I can revise the player shadow code soon.

**Comment by noaccessl** [comment]
`vjolt_player_collision_tolerance 0` will fix weird physics and chaotic rotating

**Comment by severijj** [comment]
> `vjolt_player_collision_tolerance 0` fixes weird physics and chaotic rotating

Pasting it in /Garrysmod/garrysmod/cfg/autoexec.cfg will make Garry's Mod automatically execute it on server startup

**Comment by Joshua-Ashton** [comment]
Fixed.
