### ISSUE TITLE
Game crashes when trying to start a singleplayer world / Attempting to load chromium

### ISSUE THREAD

**Issue by Chaxlotl** [Joshua-Ashton/VPhysics-Jolt#34]
crash log https://pastebin.com/G8330eG9 dont know if im just being stupid or not title says it all

**Comment by tqoac** [comment]
same thing is happening to me.

**Comment by GrayWolf64** [comment]
me too

**Comment by nnk000** [comment]
same

**Comment by Synkstar** [comment]
Its likely because your cpu doesn't support the required instructions that this is compiled with. Currently only really guaranteed to work on newer cpus. I tried older xeons but it doesn't run on those yet this is a known issue. Just crashes right after prep ok for me too on those cpus because thats when it tries to load it up. Same as #13 and #41

**Comment by Synkstar** [comment]
This has lots of crashing issues on linux and he told me that he was planning on fixing it and all this takes is changing the compiler flags so it supports those instruction sets. But we cant compile it for gmod ourselves because he works for valve and used a private csgo sdk to make it since it has the vphysics interfaces. Idk why valve doesn't have that public if the source code is leaked smh. I wouldn't say this is in a state that's ready for servers yet but if you are a large server you will be using a modern cpu. Someone could make an sdk that has the vphysics interface though using that leaked source code technically but he wouldn't be able to share it because ofc he wouldn't want to get fired over this. Would be nice because it would allow other people to work on it but we wouldnt have this if he wasnt a valve employee because no one else has gotten close to this far with a vphysics replacement.

**Comment by Joshua-Ashton** [comment]
https://github.com/Joshua-Ashton/VPhysics-Jolt/issues/46
